#!/usr/bin/python3

   
from sys import argv
if len(argv) != 2:
    exit();
file = open(argv[1], 'r')
for line in file:
    nbr = int(line)
    i = 2
    j = 2
    while nbr % i != 0:
        i += 1
    print("{}={}*{}".format(nbr, int(nbr / i), i))
file.close()
