#!/usr/bin/env bash


FILE=$1

while read NUM
do
    factors=($(factor $NUM))
    i=${#factors[@]}
    j=$(($i - 1))
    printf "$NUM=${factors[$j]}*"
    if (( $i == "2")); then
	    printf "1"
    else
    	for (( ; j>=2; j-- ))
   	 do
		 if (( "${factors[$j]}" != "${factors[$(( $j - 1 ))]}" )); then
			 printf "${factors[$(( $j - 1 ))]}"
		fi
	if (( "$(( $j - 2 ))" != "0" )); then
		printf "*"
	fi
    	done
    fi
done < $FILE
